console.log("Welcome to Typescript");
var firstname = "Tom";
var age = 33;
console.log("Name =" + firstname);
console.log("Age =" + age);
var f = 70;
var s = 80;
var c = "40";
var result = f + s + c;
var R = f + c + s;
console.log(result);
console.log(R);
